

services:
  db:
    image: 'mysql:8.4'
    command: [
      "--log-bin=mysql-bin",           # Enables binary logging
      "--binlog-format=ROW",           # Sets binlog format to ROW
      "--binlog-row-metadata=FULL",    # Ensures full row metadata       
    ]
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_DATABASE: olake
      MYSQL_ROOT_PASSWORD: olake
      MYSQL_USER: olake_user           # Added MySQL username
      MYSQL_PASSWORD: olake_password
      MYSQL_ROOT_HOST: '%'
    networks:
      - olake-test
    cap_add:
      - SYS_NICE # Prevents 'mbind: Operation not permitted' errors

networks:
  olake-test:
    name: olake-test
    external: true
