name: Integration Tests

on:
  push:
    branches:
      - "feat/testing_framework"
      - "feat/mongodb_testing"
  pull_request:
    branches:
      - "*"
      - "feat/mongodb_testing"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'
    
          
      # Start required containers
      - name: Ensure olake-test network exists
        run: |
          docker network create olake-test || true
      # Start MongoDB container
      - name: Start MongoDB container
        working-directory: drivers/mongodb
        run: |
          docker compose up -d

      - name: Wait for MongoDB healthcheck
        run: |
          for i in {1..30}; do
            if docker inspect --format='{{.State.Status}}' olake_mongo-test | grep -q running \
               && docker exec olake_mongo-test \
                  mongosh --username olake --password olake --authenticationDatabase admin \
                  --eval "db.adminCommand({ ping: 1 })" &> /dev/null
            then
              echo "MongoDB is healthy!"
              break
            fi
            echo "Waiting for MongoDB…"
            sleep 5
          done
      
      - name: Ensure init script is executable
        working-directory: drivers/mongodb
        run: chmod +x docker-compose-init.sh

      - name: Initialize replica set
        working-directory: drivers/mongodb
        run: |
          bash ./docker-compose-init.sh

      - name: Start MySQL container
        run: |
          pushd ./drivers/mysql
          docker compose up -d
          popd
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if docker exec olake_mysql-test mysql -h localhost -u root -proot1234 -e "SELECT 1" &> /dev/null; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      
      - name : Start PostgreSQL container
        run: |
          pushd ./drivers/postgres
          docker compose up -d
          popd
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if docker exec olake_postgres-test psql -h localhost -U postgres -d postgres -c "SELECT 1" &> /dev/null; then
              echo "PostgreSQL is up!"
              break
            fi
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Start Iceberg services
        run: |
          pushd ./writers/iceberg/local-test
          docker compose up -d
          popd
    
      - name: Create data directories with proper permissions
        run: |
          sudo mkdir -p /home/runner/work/olake/olake/writers/iceberg/local-test/data/postgres-data
          sudo mkdir -p /home/runner/work/olake/olake/writers/iceberg/local-test/data/minio-data
          sudo mkdir -p /home/runner/work/olake/olake/writers/iceberg/local-test/data/ivy-cache
          sudo chmod -R 777 /home/runner/work/olake/olake/writers/iceberg/local-test/data
      # Install go dependencies and build
      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      # Build Maven project
      - name: Run Maven build
        run: |
          cd ./writers/iceberg/debezium-server-iceberg-sink
          mvn clean package -DskipTests

      # Run the integration tests
      - name: Run integration tests for MySQL
        run: |
          go test -v ./drivers/mongodb/internal/... -tags=integration --timeout 0
      
      # - name: Run integration tests for MySQL
      #   run: |
      #     go test -v ./drivers/mysql/internal/... -tags=integration --timeout 0
      
      # - name: Run integration tests for PostgreSQL
      #   run: |
      #     go test -v ./drivers/postgres/internal/... -tags=integration --timeout 0
    
          
      # Clean up containers when done
      - name: Clean up Docker containers
        if: always()
        run: |
          pushd ./writers/iceberg/local-test
          docker compose down
          popd
          
          pushd ./drivers/mysql
          docker compose down
          popd