name: MySQL Integration Tests

on:
  push:
    branches:
      - "feat/testing_framework"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mysql
          MYSQL_USER: mysql
          MYSQL_PASSWORD: secret1234
          MYSQL_ROOT_PASSWORD: rootsecret
        ports:
          - 3306:3306
        # Use hyphens for MySQL command-line options
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u mysql -psecret1234"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --server-id=1
          --log-bin=mysql-bin
          --binlog-format=ROW
          --binlog-row-image=FULL
          --binlog-row-metadata=FULL # Corrected: This option seems correct as per MySQL 8 docs for binlog metadata
          --max-allowed-packet=256M  # Corrected: underscore to hyphen
          --innodb-buffer-pool-size=512M # Corrected: underscore to hyphen
          --default-authentication-plugin=mysql_native_password # This one was already correct

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Adjust to your Go version

      - name: Install dependencies
        run: go mod download

      - name: Initialize MySQL schema
        run: |
          mysql -h 127.0.0.1 -u mysql -psecret1234 mysql < drivers/mysql/docker-entrypoint-initdb.d/init.sql
        env:
          MYSQL_PWD: secret1234

      - name: Run tests
        run: go test -v ./drivers/mysql/internal